USE [ADE]
GO

/****** Object:  Table [dbo].[Salones]    Script Date: 14/02/2024 08:00:21 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Salones](
	[id_salon] [int] IDENTITY(1,1) NOT NULL,
	[nom_salon] [nchar](100) NOT NULL,
 CONSTRAINT [PK_Salones] PRIMARY KEY CLUSTERED 
(
	[id_salon] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

